<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Dispenser" Id="{21bb3e3f-b2bc-4806-8e5c-60024680aa77}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Dispenser
VAR_INPUT
	bEnable :BOOL;
	bExecute :BOOL;
	rDistance :REAL;
END_VAR
VAR_OUTPUT
	eState :eBetriebszustand;
END_VAR
VAR
	mc_Reset :MC_Reset;
	mc_Power :MC_Power;
	mc_MoveRelative :MC_MoveRelative;
	nState :INT :=0;
END_VAR
VAR_IN_OUT
	ax :Axis_Ref;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ax.ReadStatus();
mc_Reset(
	Axis:= ax, 
	Execute:= , 
	Done=> , 
	Busy=> , 
	Error=> , 
	ErrorID=> );
	
mc_Power(
	Axis:= ax, 
	Enable:= , 
	Enable_Positive:= , 
	Enable_Negative:= , 
	Override:= , 
	BufferMode:= , 
	Options:= , 
	Status=> , 
	Busy=> , 
	Error=> , 
	ErrorID=> );
	
mc_MoveRelative(
	Axis:= ax, 
	Execute:= , 
	Distance:= rDistance, 
	Velocity:= 60, 
	Acceleration:= 30, 
	Deceleration:= 30, 
	Jerk:= , 
	BufferMode:= , 
	Options:= , 
	Done=> , 
	Busy=> , 
	Active=> , 
	CommandAborted=> , 
	Error=> , 
	ErrorID=> );
	

IF NOT bEnable THEN
	nState:=0;
END_IF

CASE nState OF 
	0:
	eState:=eBetriebszustand.Off;
	mc_Power.Enable :=TRUE;
	mc_Power.Enable_Positive:=TRUE;
	
	
	IF bEnable AND NOT mc_power.Status THEN
		nState :=10;
	ELSIF mc_power.Status AND bEnable THEN
		nState:=20;
	END_IF
	
	10: // init Reset
	eState:=eBetriebszustand.Init;
	mc_Reset.Execute:=TRUE;
	
	IF mc_Reset.Done THEN
		nState:=11;
	END_IF
	
	11: // init Power
	eState:=eBetriebszustand.Init;
	mc_Reset.Execute:=FALSE;
	mc_Power.Enable :=TRUE;
	mc_Power.Enable_Positive:=TRUE;
	
	
	IF mc_Power.Status THEN
		nState:=20;
	END_IF
	
	20: // Ready
	eState:= eBetriebszustand.Ready;
	
	IF bExecute THEN 
		nState:=30;
	END_IF
 
	30: // Kontinuierliche Bewegung
	eState:=eBetriebszustand.Production;
	mc_MoveRelative.Execute :=TRUE;
	
	IF mc_MoveRelative.Done THEN 
		mc_MoveRelative.Execute:=FALSE;
		nState :=40;
	END_IF
	
	40: // Fertig
	eState :=eBetriebszustand.Done;
	
	IF NOT bExecute THEN 
		nState:=20;
	END_IF

END_CASE]]></ST>
    </Implementation>
    <LineIds Name="FB_Dispenser">
      <LineId Id="22" Count="20" />
      <LineId Id="184" Count="0" />
      <LineId Id="169" Count="14" />
      <LineId Id="166" Count="1" />
      <LineId Id="298" Count="0" />
      <LineId Id="297" Count="0" />
      <LineId Id="299" Count="1" />
      <LineId Id="80" Count="1" />
      <LineId Id="187" Count="2" />
      <LineId Id="277" Count="0" />
      <LineId Id="274" Count="0" />
      <LineId Id="190" Count="9" />
      <LineId Id="201" Count="7" />
      <LineId Id="278" Count="0" />
      <LineId Id="209" Count="0" />
      <LineId Id="275" Count="0" />
      <LineId Id="210" Count="13" />
      <LineId Id="254" Count="0" />
      <LineId Id="225" Count="1" />
      <LineId Id="255" Count="0" />
      <LineId Id="227" Count="2" />
      <LineId Id="248" Count="1" />
      <LineId Id="251" Count="2" />
      <LineId Id="185" Count="0" />
      <LineId Id="149" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>