<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Vereinzelung" Id="{7a9d22e3-c8af-4ad6-af31-eb8b2416cf06}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Vereinzelung
VAR_INPUT
	//Steuervariablen
	bEnable :BOOL;
	bExecute :BOOL;
	
	//Hardwareeingänge
	bSens1 :BOOL; //Flasche in der Kammer
	bSens2 :BOOL; //Flasche im Rohr
	bSens3 :BOOL; //Flasche verkehrt
	bSens4 :BOOL; //Flasche am Förderband
END_VAR
VAR_OUTPUT
	//Steuervariable 
	eState :eBetriebszustand;
	
	//Hardwareausgägne
	bGate1 :BOOL;
	bGate2 :BOOL;
END_VAR
VAR
	nState :INT :=100;
	fbTON :TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbTON(IN:= , PT:= T#2S, Q=> , ET=> );

IF NOT bEnable THEN
	nState :=0;
END_IF

CASE nState OF
	100: //Off oder nicht Betriebsbereit 
	eState:=eBetriebszustand.Off;
	
	IF bSens1 AND bEnable THEN
		nState:=21; //Ready
	ELSIF bEnable THEN
		nState :=0; //Init
	END_IF
	
	
	0: //Kammer ist leer
	eState:=eBetriebszustand.Init;
	
	bGate1:=FALSE;
	bGate2:=FALSE;
	
	IF bSens2 THEN
		nState:=1; //Oben öffnen
	END_IF
	
	
	1: //Oben öffnen
	eState := eBetriebszustand.Init;
	
	bGate1:=TRUE;
	bGate2 :=FALSE;
	
	IF bSens1 THEN
		nState:=2; //Oben schleißen
	END_IF
	
	
	2: //Oben schließen
	eState := eBetriebszustand.Init;
	
	bGate1:=FALSE;
	bGate2 :=FALSE;
	fbTon.IN:=TRUE;
	
	IF fbTon.Q THEN
		nState:=21; //Ready
		fbTon.IN :=FALSE;
	END_IF
	
	21: //Ready
	eState := eBetriebszustand.Ready;
	
	bGate1:=FALSE;
	bGate2 :=FALSE;
	
	IF bExecute THEN
		nState:=3; //Unten öffnen
	END_IF
	
	
	3: //Unten öffnen
	eState := eBetriebszustand.Production;
	
	bGate1:=FALSE;
	bGate2 :=TRUE;
	
	IF bSens4 THEN
		nState :=4; //Unten schließen
	END_IF
	
	4: //Unten schließen
	eState := eBetriebszustand.Production;
	
	bGate1:=FALSE;
	bGate2 :=FALSE;
	fbTon.IN :=TRUE;
	
	IF fbTon.Q THEN
		nState:=41; //Done
		fbTon.IN :=FALSE;
	END_IF
	
	41: //Done
	eState:= eBetriebszustand.Done;
	
	IF NOT bExecute THEN
		nState :=0; //Kammer leer
	END_IF
	
	
END_CASE]]></ST>
    </Implementation>
    <LineIds Name="FB_Vereinzelung">
      <LineId Id="28" Count="0" />
      <LineId Id="143" Count="0" />
      <LineId Id="168" Count="2" />
      <LineId Id="29" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="49" Count="3" />
      <LineId Id="55" Count="1" />
      <LineId Id="53" Count="1" />
      <LineId Id="32" Count="1" />
      <LineId Id="58" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="60" Count="1" />
      <LineId Id="64" Count="3" />
      <LineId Id="62" Count="0" />
      <LineId Id="34" Count="1" />
      <LineId Id="68" Count="2" />
      <LineId Id="72" Count="4" />
      <LineId Id="71" Count="0" />
      <LineId Id="36" Count="1" />
      <LineId Id="78" Count="3" />
      <LineId Id="85" Count="0" />
      <LineId Id="82" Count="2" />
      <LineId Id="86" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="42" Count="1" />
      <LineId Id="87" Count="0" />
      <LineId Id="93" Count="2" />
      <LineId Id="89" Count="3" />
      <LineId Id="88" Count="0" />
      <LineId Id="38" Count="1" />
      <LineId Id="96" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="97" Count="1" />
      <LineId Id="100" Count="3" />
      <LineId Id="99" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="106" Count="2" />
      <LineId Id="105" Count="0" />
      <LineId Id="104" Count="0" />
      <LineId Id="109" Count="0" />
      <LineId Id="111" Count="2" />
      <LineId Id="110" Count="0" />
      <LineId Id="47" Count="1" />
      <LineId Id="114" Count="4" />
      <LineId Id="40" Count="1" />
      <LineId Id="31" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>